services:
  linkstack:
    image: linkstackorg/linkstack:latest
    restart: unless-stopped
    ports:
      - "${COOLIFY_LINKSTACK_PORT:-8080}:80"
      - "${COOLIFY_LINKSTACK_SSL_PORT:-8081}:443"
    environment:
      - TZ=${TZ:-Europe/Berlin}
      - SERVER_ADMIN=${SERVER_ADMIN:-admin@example.com}
      - HTTP_SERVER_NAME=${HTTP_SERVER_NAME:-example.com}
      - HTTPS_SERVER_NAME=${HTTPS_SERVER_NAME:-example.com}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-256M}
      - UPLOAD_MAX_FILESIZE=${UPLOAD_MAX_FILESIZE:-8M}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - type: bind
        source: ${COOLIFY_VOLUME_LINKSTACK:-./data/linkstack}
        target: /htdocs
    user: apache:apache
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-linkstack}
      - MYSQL_USER=${MYSQL_USER:-linkstack}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - type: bind
        source: ${COOLIFY_VOLUME_MYSQL:-./data/mysql}
        target: /var/lib/mysql
